### ISSUE TITLE
Selecting task node to view logs leads to blank page

### ISSUE THREAD

**Issue by JLSteenwyk** [latchbio/latch#121]
Hi,

While developing a workflow (`OrthoSNAP/0.0.25-c77189`), I ran a test execution but it failed (`fc9e65bb404f26953`). To see the log files, I clicked on the task node but it led to a blank page.

**Comment by JLSteenwyk** [comment]
[screen-capture.webm](https://user-images.githubusercontent.com/17225603/180660068-a8a9b428-a1f1-442d-82f8-17521a81e5b5.webm)

**Comment by kennyworkman** [comment]
i've identified this as `Optional[Enum]` breaking our protobuf parser in the console, working on a patch

**Comment by kennyworkman** [comment]
this has been resolved
