### ISSUE TITLE
get-params generates Enum with incorrect attribute names

### ISSUE THREAD

**Issue by jvfe** [latchbio/latch#137]
- **Python version**: 3.10.5
- **Latch SDK version**: 1.14.0

In one of my workflows I have a parameter which is an Enum type:

```py
from enum import Enum

class taxon_rank(Enum):
    superkingdom = 'superkingdom'
    phylum = 'phylum'
    taxon_class = 'class'
    order = 'order'
    family = 'family'
    genus = 'genus'
    species = 'species'
```
Notice the taxon_class attribute, which I named like this since 'class' is a reserved word in Python. The value itself still has to be 'class' since this is the value the CLI tool expects.

When I run get-params with this workflow, it generates a param file with this Enum as one of its types:

```py
from enum import Enum

class taxon_rank(Enum):
    superkingdom = 'superkingdom'
    phylum = 'phylum'
    class = 'class'
    order = 'order'
    family = 'family'
    genus = 'genus'
    species = 'species'
```

taxon_class is renamed to 'class', which generates errors when launching the workflow.

It's simple enough for me to fix in my param file but it would be best to fix the root cause, which I think is located somewhere in [here](https://github.com/latchbio/latch/blob/a83f7281310cca933964d511e90b4e72f0f8f233/latch_cli/services/get_params.py#L120-L121).

**Comment by kennyworkman** [comment]
`latch get-params` transforms serialized versions of each type back to their python representation. The serialized type is language independent and can have structure that is different from python. For enums, the serialized type lacks the "names" for each variant so we guess them when we convert it to python.

Will push a patch to make prefix names with a `_` if they are reserved identifiers
