### ISSUE TITLE
[BUG] Can't latch exec into tasks

### ISSUE THREAD

**Issue by hannahle** [latchbio/latch#148]
When clicking on a task of a workflow I registered, I only see `latch exec null` instead of the actual task ID. 

See screenshot below:
<img width="846" alt="Screen Shot 2022-08-30 at 3 54 51 PM" src="https://user-images.githubusercontent.com/30064991/187530871-0e73175b-bb59-4207-95d9-46980dfa19a3.png">

**Comment by kennyworkman** [comment]
resolved a while ago
