### ISSUE TITLE
Better registration error message for users who haven't logged in to Latch

### ISSUE THREAD

**Issue by hannahle** [latchbio/latch#159]
When a user has not logged into Latch and don't have a browser token on their machine, registering a workflow results in "Unable to find pkg version" which is inaccurate. 

Return a message that asks people to latch login instead.

**Comment by ayushkamat** [comment]
Fixed in https://github.com/latchbio/latch/commit/6c917bafe4ede0fb8a99681e3bd24109f4030f4f
