### ISSUE TITLE
"Publish to all workflows" button not updating after clicking it

### ISSUE THREAD

**Issue by jvfe** [latchbio/latch#170]
**Describe the bug**
After clicking the "Publish to All Workflows" button, the button doesn't update to "Remove from all workflows" and I can't get the shareable link. After clicking and refreshing the console, then the button changes and the link shows up.

**To Reproduce**
1. Go to an unpublished workflow in the console
2. Click on the "Publish to all workflows" button
3. The button didn't update and you didn't get a shareable link
4. Refresh the page
5. Now the button has updated.

**Expected behavior**
I expect the "Publish to all workflows" button to be reactive, e.g., after clicking it, it changes to be "Remove from all workflows"

**Screenshots**

Clicked the button:
![image](https://user-images.githubusercontent.com/43506501/190708311-93f167f3-cdfd-46a8-a17b-3ed117528923.png)

After clicking and refreshing, now it's updated:
![image](https://user-images.githubusercontent.com/43506501/190708444-34b95d8f-a1b3-43f0-94ff-d083bc5ac3e9.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: 104.0.2

**Comment by kennyworkman** [comment]
should be resolved
