### ISSUE TITLE
Docs: Best practices for writing a Latch workflow

### ISSUE THREAD

**Issue by hannahle** [latchbio/latch#175]
**Is your feature request related to a problem? Please describe.**
When starting, users often adopt code practices from other examples that might not be the best. Further, users don't always look at all samples and stop at the "Authoring my Workflow" on Quickstart. 

**Describe the solution you'd like**
We should introduce an additional section of best practices, which can include: 
- How to work correctly with LatchFile and LatchDir the first time. 
- How to make your code more modular to avoid cluttering the __init__.py (Dockerfile per task, subworkflows)

Each recommendation should link to a good, concise example.

**Comment by kennyworkman** [comment]
completed
