### ISSUE TITLE
Implement dockerfile argument in Latch tasks

### ISSUE THREAD

**Issue by jvfe** [latchbio/latch#189]
**Is your feature request related to a problem? Please describe.**

Currently, when trying to use the dockerfile-per-task feature in the Latch SDK, you can't use the 'dockerfile=' argument
inside the SDK decorator, e.g. `@small_task(dockerfile=Path(...))`. If you try to use this in version 2.6.3, the serialization will fail with a TypeError being raised: `wrapper() got an unexpected keyword argument 'dockerfile'`

**Describe the solution you'd like**
It would be better to allow users to use task-specific dockerfiles with native SDK tasks, instead of having to import the task decorator from flytekit. 

**Describe alternatives you've considered**
This is how I'm using task-specific dockerfiles atm:
```py
from flytekit import task
from latch.resources.tasks import _get_large_pod, _get_small_pod

@task(
    task_config=_get_small_pod(),
    dockerfile=Path("path to dockerfile")
)
...
```

**Comment by kennyworkman** [comment]
@jvfe this should be resolved with the latest version of latch - [reference](https://docs.latch.bio/basics/writing_dockerfiles.html#writing-dockerfiles-for-different-tasks).

If this does not work for you, can you please open another issue.
