### ISSUE TITLE
Ability to create files within the latch console GUI

### ISSUE THREAD

**Issue by CamelCaseCam** [latchbio/latch#202]
**Is your feature request related to a problem? Please describe.**
It isn't well documented that you can use `latch touch` to create remote files from the command line. It would be better if, like with folders, you could create files in the GUI. 

**Describe the solution you'd like**
I'd like there to be a button or some sort of dialogue, like for folders, but to create files from the latch GUI. You'd navigate to a folder and then click the button to create the file. 

**Describe alternatives you've considered**
`latch touch` does this already, but you have to go to the CLI documentation to find it, and it feels nicer from a UX perspective if the user doesn't have to use the command line to create files.

**Comment by kennyworkman** [comment]
appreciate the feedback - will pass it on to @hannahle 
however lets make sure issues opened here are directly relevant to the SDK moving forward (you can message us on slack for general platform features)
