### ISSUE TITLE
Biocomputing Recipies nf-core/rnaseq ETA

### ISSUE THREAD

**Issue by jwarnn** [latchbio/latch#41]
Hello I am possibly interested in using your platform and I am largely a user of custom Nextflow scripts, nf-core scripts, and other publicly available Nextflow scripts. While I can see a plausible path into integrating some of these scripts on to your platform; an example would be extremely helpful in determining the amount of work that would go into it. Is there an ETA on when the biocomputing recipie for nf-core/rnaseq ? Just the code that was used to create the workflow would be very helpful.

**Comment by kennyworkman** [comment]
hi @jwarnn sorry for the delay - here is some code for a more complex native workflow - https://github.com/latch-verified/bulk-rnaseq

we are in the process of building a nextlflow -> latch code transpiler and will update you when that feature is complete
