### ISSUE TITLE
Add ability to use @dynamic or map_task functionality from Flyte

### ISSUE THREAD

**Issue by ricomnl** [latchbio/latch#51]
Wrap `@dynamic` in latch (https://blog.flyte.org/dynamic-workflows-in-flyte). If used, it's currently not recognized as a workflow.
An alternative would be `map_task`: https://towardsdatascience.com/map-tasks-in-flyte-47f198c1772e but ideally both are supported

**Comment by hannahle** [comment]
Closing because dynamic and map tasks are released in [v1.3.0](https://github.com/latchbio/latch/releases/tag/v1.3.0)
