### ISSUE TITLE
input file validation is not working as expected

### ISSUE THREAD

**Issue by nahid18** [latchbio/latch#56]
I have included a file validation criteria for `.conf` file with `Annotated` and `FlyteMetadata`.
However, in production, the file regex doesn't work as intended.

Code snippet:
```
@workflow
def shasta(
    input_dir: LatchDir,
    config: Annotated[
            LatchFile,
            FlyteMetadata(
                {
                    "rules": [
                        {
                            "regex": "(.conf)$",
                            "message": "Only .conf extensions are valid",
                        }
                    ]
                }
            ),
        ],
) -> (LatchFile, LatchDir):
```

Full code: https://github.com/nahid18/shasta/blob/main/wf/__init__.py
Production tool to check the issue live: `wf.shasta` v1.0.8 workflow on LatchBio

**Comment by ayushkamat** [comment]
What do you mean by 'doesn't work as intended'? Please provide 

(1) What you wanted to happen (what you intended)
(2) What actually happened
