### ISSUE TITLE
Cannot install latch via pip on M1 macs

### ISSUE THREAD

**Issue by shivaramakrishna99** [latchbio/latch#62]
`python3 -m pip install latch` or `pip install latch` with Docker running on an M1 mac result in the following error where numpy fails to install.  Tried fixing using `pip install -U wheel` and `pip install -U setuptools`, but it does not work.

![image](https://user-images.githubusercontent.com/43115032/170251774-ac8847f1-be09-4bb0-86ff-53c0b4d1bf95.png)`

Similar to issue #43

**Comment by shivaramakrishna99** [comment]
hi @SSP231211, thanks for your response.  I tried the installation with Python 3.8.9 (native distribution on Mac) and with Python 3.9 (Homebrew distribution). It seems as though numpy and pyarrow are two dependencies that do not yet run properly on the M1 Macs.

**Comment by kennyworkman** [comment]
#64 might have resolved this

**Comment by kennyworkman** [comment]
@shivaramakrishna99

**Comment by kennyworkman** [comment]
pushed a patch release versioned `v0.9.2` that stripped `pyarrow` from the dependency list. can you try installing that?
