### ISSUE TITLE
Can not install latch via pip in windows 11

### ISSUE THREAD

**Issue by SSP231211** [latchbio/latch#63]
I have used the following commands 
1. pip install latch  
# Upgrades pip and Downloaded Visual Studio Tools as well
2. C:\Users\Surendra\AppData\Local\Programs\Python\Python310\python.exe -m pip install latch 
![latch installation problem](https://user-images.githubusercontent.com/106246031/170257153-3611a07f-95e2-427d-8247-cd0fa82942e5.png)

**Comment by SSP231211** [comment]
Hi, the error was because of latest version of python, because latch supported by the python versions less than 3.9.0. That's why I uninstalled latest version and installed python 3.8.9 using following link and worked well.
https://www.python.org/downloads/release/python-389/

**Comment by kennyworkman** [comment]
glad you got it installed
