### ISSUE TITLE
Add option to email reports to users 

### ISSUE THREAD

**Issue by GeOdette** [latchbio/latch#72]
Allow users to easily access their reports for publications via email. Add an emailing option at the console.

**Comment by hannahle** [comment]
Hi George! What if we have Email notification for when your workflow finishes executing, and in the email, we include links to the outputs of that workflow? Would this also work?

**Comment by GeOdette** [comment]
That also seem a good option. Though sounds like making the user take many rounds before accessing results. Also you can add option to allow users select which reports they emailed to them. To avoid spamming wrong emails when user mystype their emails, perhaps think of sending reports to the default email users registered with as well as email entered at the console.

**Comment by hannahle** [comment]
Noted. I'll add this to the backlog.

**Comment by kennyworkman** [comment]
there is no current plan to implement this feature
