### ISSUE TITLE
Avoiding duplicates

### ISSUE THREAD

**Issue by GeOdette** [latchbio/latch#73]
Can there be a way to avoid duplicating tools (especially for wfs with single tools) being duplicated at latch? These tools can be duplicated in work flows that are robust but might not be relevant if duplicated as single tools. E.g author0 and author1 both uploading fastqc under different names. While the operationability might differ based on the authors scripting style, I think a synchronization can be lavaraged to ensure the most efficient use without duplicating.

**Comment by ayushkamat** [comment]
We don't really see this as something we want to do going forward, seeing as there is a huge amount of variability and no solution for it is truly robust. In some sense I also don't really see this as being an issue, as anyone looking to upload a workflow can search through existing publicly available workflows and see for themselves.
