### ISSUE TITLE
Allow good directions of the workflows

### ISSUE THREAD

**Issue by GeOdette** [latchbio/latch#76]
Suggest you improve the publish button to allow wf developers channel their wf to the correct folder or group ( ignore if the feature currently exists, if it does perhaps show how it's done?) if a user onboards a wf that cannot be contained in any existing directories, then allow user to create a new folder and publish the wf there. For instance, a  wf on crispr should exist in the crispr directory (as currently is) but I can't seem to find a way of directing my crispr wf to this directory.

**Comment by ayushkamat** [comment]
We now support tags in workflow metadata, that accomplish something similar.
