### ISSUE TITLE
Can the docstring in __init__.py be replaced with a separate YAML file that can be imported?

### ISSUE THREAD

**Issue by shivaramakrishna99** [latchbio/latch#88]
Or a markdown file such as `interface.md` that takes in description and args via frontmatter

**Comment by shivaramakrishna99** [comment]
Or a markdown file such as `interface.md` that takes in description and args via frontmatter

**Comment by ayushkamat** [comment]
@shivaramakrishna99 to clarify, this issue has been changed due to the `LatchMetadata` constructs to now be an `About.md` file which contains the long-form documentation of the workflow itself - just to confirm, are you still working on implementing this?

**Comment by kennyworkman** [comment]
closing this @shivaramakrishna99 because the `LatchMetadata` object solves this problem. please flag if you don't feel this is the case
