### ISSUE TITLE
Workflow metadata and interface on latch console not produced properly by python code

### ISSUE THREAD

**Issue by uniformelk1** [latchbio/latch#91]
@kennyworkman : The plotseqdata workflow I have developed has been initialised and registered to the latch console. However, the code within the @worfklow function within the __init__.py file containing all of the necessary metadata to produce the console interface for the console does not seem to create the right interface.

Also, image of my code for workflow local development is attached as there are issues with flytekit dependencies (error message also attached):
<img width="525" alt="Screenshot 2022-06-26 at 21 00 17" src="https://user-images.githubusercontent.com/95243818/175831802-bb2359b2-7846-4954-ac63-cb2efd993dd3.png">

Python 3.8.5
Flytekit 1.0.5
Latch 1.3.2

**Comment by ayushkamat** [comment]
This is due to using `flytekit` instead of our fork, `lytekit`. Uninstall both `latch` and `flytekit` and reinstall `latch` - this will automatically install `lytekit`.
